function imageData = typhoon_gel_to_tiff(imageData, varargin)
%% transforms typhoon laserscanner .gel format data to linear, absolute intensity values
%   INPUTS: 
%   imageData structure generated by load_gel_image function

%   OUTPUT:
%   imageData struct with .images .images_gel .images_tiff .pathnames .filenames .nrImages
%   .nrImages is number of images
%   .images is cell array {nr_image} of image data in linear LAU format
%   .images_gel_format is cell array {nr_image} of image data in square-root .gel format
%   .images_tiff_format is cell array {nr_image} of image data in linear-with-constant-offset .tiff format
%   .pathnames is cell array {nr_image} of pathnames to each image
%   .filenames is cell array {nr_image} of filenames of each image

%% calculate LAU format values from .gel format
images_LAU = cell(imageData.nrImages, 1);

%standard values for the ZNN typhoon laserscanner:
%LAU value for QL=0
pix = 25;
L = 5;
G = 65536;
LAU_0 = (pix / 100)^2 * 100 * 10^(L * (0/G - 0.5));
LAU_65535 = (pix / 100)^2 * 100 * 10^(L * (65535/G - 0.5));

for i = 1 : imageData.nrImages
    images_LAU{i} = (imageData.images{i} .* ((sqrt(LAU_65535) - sqrt(LAU_0)) / 65535) + sqrt(LAU_0)) .^ 2;
end


%% calculate tiff format values from .gel format
images_tiff = cell(imageData.nrImages, 1);

for i = 1 : imageData.nrImages
    LAU_max = max(max(images_LAU{i}));
    
    %sorted array of unique values in LAU data
    values_in_LAU_data = sort(unique(images_LAU{i}(:)));
    
    if max(max(imageData.images{i})) == 65535
        'tiff scaled to 65535'
        images_tiff{i} = 62258/(values_in_LAU_data(end-1) - LAU_0) .* (images_LAU{i} - LAU_0);
        %values above max_non_saturated_value are set to 65535
        max_non_saturated_value = 62258/(values_in_LAU_data(end-1) - LAU_0) .* (values_in_LAU_data(end-1) - LAU_0);
        images_tiff{i}(images_tiff{i} > max_non_saturated_value) = 65535;
    else
        'tiff scaled to 62258'
        images_tiff{i} = 62258/(LAU_max - LAU_0) .* (images_LAU{i} - LAU_0);
    end
end

%% add different image formats to imageData structure, return imageData structure
imageData.images_gel_format = imageData.images;
imageData.images_tiff_format = images_tiff;
imageData.images = images_LAU;

end